### ISSUE TITLE
Weekly Scrum - February 27th

### ISSUE THREAD

**Issue by VarunSriram** [scotthanton/Competency-Tracker#2]

**Comment by scotthanton** [comment]
**What have I done this week?**
This week I have setup our vagrant virtual development environment and configured the vagrant setup file. I have also setup our basic bare-bones rails application.

**What will I do next week ?**
Next week I will begin structuring our application, defining the database scaffolding and beginning to define which controllers we will need for our application.

**Comment by jsinoimeri** [comment]
**What have I done this week?**
This week I deployed the rails application that Scott created to Heroku with help from Varun. I also created and submitted the required document on CULearn.

What will I do next week?
Next week I will start implementing the first few features for our application by using scaffolding as well creating some tests for those features.

**Comment by VarunSriram** [comment]
**What have I done this week?**

This I helped setup our issue tracking on git for out group members to use, and also helped identifying and fixing with some of the compatibility issues with our app when attempting to deploy our app on Heroku. These issues were fixed by converting out databases from SQLite to PostGres.

**What will I do next week?**
Next week I will begin implementing our first feature of milestone 2 which is  a prototype of our user login system for of our app. This will involve designing a user model, and distinguishing them between employers and employees.

**Comment by tosbak1** [comment]
What have I done this week?
This week I wrote the Readme.md file which contains the initial description of the app being build and the first feature to be developed. 

What will I do next week?
Next week I will start with developing the first feature of the app and also the structure the application.
